In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.1'

## Create & Read

### 1D Array

In [3]:
arr1 = np.array([1,2,3,4,5])

In [4]:
arr1

array([1, 2, 3, 4, 5])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr1.shape

(5,)

In [7]:
arr1.dtype

dtype('int64')

In [8]:
arr1.ndim

1

In [9]:
arr1.size

5

### 2D Array

In [13]:
arr2 = np.array([[1,2,3], [2,3,4]])
arr2

array([[1, 2, 3],
       [2, 3, 4]])

In [14]:
arr2.ndim

2

In [15]:
arr2.shape #(2row and 3column)

(2, 3)

In [16]:
arr2.dtype

dtype('int64')

In [17]:
arr2.size

6

### 3D Array

In [19]:
arr3 = np.array([[[1,2,3], [3,4,5]], [[5,6,7],[6,9,1]]]) 
arr3

array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [6, 9, 1]]])

In [20]:
arr3.ndim

3

In [21]:
arr3.shape #2 is no. of layer, 2row in each layer and 3columns in each layer

(2, 2, 3)

In [22]:
arr3.size

12

### random array

In [26]:
randArr = np.random.rand(3, 2, 3)
randArr

array([[[0.1975463 , 0.48687512, 0.92478008],
        [0.07401486, 0.53356259, 0.15597446]],

       [[0.09734863, 0.0949687 , 0.1381195 ],
        [0.97424419, 0.2873612 , 0.33685878]],

       [[0.76334617, 0.74801939, 0.98530157],
        [0.42950679, 0.29270981, 0.04917359]]])

In [27]:
randArr.dtype

dtype('float64')

In [28]:
zeroes = np.zeros((3,2,3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [29]:
zeroes.ndim

3

In [30]:
full = np.full((3,2,3), 8)
full

array([[[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]]])

In [33]:
ones = np.ones((3,2,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [34]:
arr3

array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [6, 9, 1]]])

In [35]:
arr3[0]

array([[1, 2, 3],
       [3, 4, 5]])

In [36]:
arr3[0][0]

array([1, 2, 3])

In [39]:
arr3[0][1]

array([3, 4, 5])

In [42]:
arr3[0][1][2]

np.int64(5)

In [43]:
arr3[2:3]

array([], shape=(0, 2, 3), dtype=int64)

In [44]:
arr3[0:2]

array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [6, 9, 1]]])

In [45]:
arr3[-1]

array([[5, 6, 7],
       [6, 9, 1]])

### Update & Delete

In [49]:
a1 = np.random.rand(2,3,2)
a2 = np.random.rand(2,3,2)
a1, a2

(array([[[0.83874507, 0.53589998],
         [0.86203608, 0.47667698],
         [0.28667114, 0.11996162]],
 
        [[0.28623664, 0.56481449],
         [0.87257453, 0.32643243],
         [0.45341739, 0.41344218]]]),
 array([[[0.77937571, 0.92927353],
         [0.76623637, 0.97320669],
         [0.17982209, 0.67687168]],
 
        [[0.80964437, 0.49329977],
         [0.68418535, 0.91007438],
         [0.52394216, 0.70258766]]]))

In [50]:
np.add(a1,a2)

array([[[1.61812078, 1.4651735 ],
        [1.62827245, 1.44988367],
        [0.46649323, 0.7968333 ]],

       [[1.09588101, 1.05811426],
        [1.55675989, 1.23650682],
        [0.97735955, 1.11602984]]])

### Update

In [51]:
arr3

array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [6, 9, 1]]])

In [53]:
arr3[0,0, 2] = 200
arr3

array([[[  1,   2, 200],
        [  3,   4,   5]],

       [[  5,   6,   7],
        [  6,   9,   1]]])

In [55]:
arr3.sort()
arr3

array([[[  1,   2, 200],
        [  3,   4,   5]],

       [[  5,   6,   7],
        [  1,   6,   9]]])